[server]
headless = true
runOnSave = true
allowRunOnSave = true
fileWatcherType = "auto"

[theme]
primaryColor="#58b190"
backgroundColor="#c7e8dc"
secondaryBackgroundColor="#8abba9"
textColor="#000000"
